### ISSUE TITLE
Just a unrelated question.

### ISSUE THREAD

**Issue by TheR0b0tMan** [OtterCodes101/NotSoEssentials#1]
Hi! So i was looking through replit projects and found this project called Lcraft 1.16. It said you helped with it. Well, I was just wondering if you were still working on it?

**Comment by OtterCodes101** [comment]
no, i'm not working on it anymore. in fact, the project is dead.

**Comment by OtterCodes101** [comment]
also, the entire project was just [ViaVersion](https://github.com/ViaVersion/ViaVersion)

**Comment by TheR0b0tMan** [comment]
Oh, ok. Thanks!
